# Generated by Django 3.2.12 on 2022-09-15 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reason',
            name='occasion',
            field=models.CharField(choices=[('S', 'Sports'), ('C', 'Casual'), ('F', 'Formal')], default='S', max_length=1),
        ),
    ]
