# Generated by Django 3.2.12 on 2022-09-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220915_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reason',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='shoe',
            name='cloths',
            field=models.ManyToManyField(to='main_app.Cloth'),
        ),
    ]
